### PR TITLE
feat: add mixin create

### PR DESCRIPTION
**Pull request by devalexandre**
Create Mixin generator command line

### CODE REVIEW

**Comment by devalexandre** [comment]
@icebob was something missing?

**Comment by icebob** [comment]
I don't know, but it contains a lot of changes and I had no capacity to check it yet. Sorry, please be patient.

**Comment by AndreMaz** [comment]
I removed ` --detectOpenHandles --forceExit` as these should not be necessary if all tests are properly implemented.
After that I've executed `npm test`  and got this 
image

**Comment by devalexandre** [comment]
> I removed ` --detectOpenHandles --forceExit` as these should not be necessary if all tests are properly implemented. After that I've executed `npm test` and got this image

I'm going to write this text, I think something is still asynchronous.

**Comment by devalexandre** [comment]
> I removed ` --detectOpenHandles --forceExit` as these should not be necessary if all tests are properly implemented. After that I've executed `npm test` and got this image


the test is not spelled wrong, but yargs is using promises, this is the test's problem, how to handle promises without forcing the output.

I'm researching about it, but I accept suggestions.

**Comment by devalexandre** [comment]
closed, to split the changes into small PRs.

**Pull request closed without merging**
