### PR TITLE
feat: update struct for add others types on create method

### PR DESCRIPTION
**Pull request by devalexandre**
Modify the structure of the create method, to facilitate the creation of other types, like Mixin. 
This structure is also reflected in the organization of tests, so that each type added for creation will have its source and tests totally separately. 
This PR refers to the [PR](https://github.com/moleculerjs/moleculer-cli/pull/50) where the creation of Mixin was included, but because there are many changes, it decides to close the old one and create a new smaller one, in 2 steps, this is the first one that deals with the reorganization of directories and files related to creation.

### CODE REVIEW

**Comment by AndreMaz** [comment]
Hey @devalexandre 

How can I create a service with a different name?

I'm trying `npm run dev create service MY-SERVICE` but it doesn't seem to work. It always creates a service called `create.service.js`

image

Also, how to create a TS template? The  ` --typescript` flag doesn't seem to work

**Comment by devalexandre** [comment]
> did you test in https://i.ibb.co/gtmdgJG/2022-03-12-13-47-59.gif branch?

**Comment by AndreMaz** [comment]
Ups! My bad. I was on master. 

JS service creation works as expected 👍 

Regarding TS. This is the correct command?
```
npm run dev create service ts --typscript
```

**Comment by devalexandre** [comment]
> npm run dev create service ts --typscript

@AndreMaz the command is

image

**Comment by devalexandre** [comment]
> > did you test in  branch?
> 
> 

sorry for the resolution, I ended up losing the link where it records with a better quality

**Comment by devalexandre** [comment]
@AndreMaz any news about esa  PR ?

**Comment by AndreMaz** [comment]
Sorry for delay @devalexandre 

Tested here and things seems to be working 👍 

One question: What the purpose of `javascript.template`  and `service.template`? Both of them seem to be identical. Same question for the `typescript.service` and `typescript.template`

image

**Comment by devalexandre** [comment]
sorry, @AndreMaz  I ended up leaving the files, but they were already removed and renamed to make it easier to understand.

**Pull request merged**
